### ISSUE TITLE
Réutilisation

### ISSUE THREAD

**Issue by minch4** [Thosbk/DivideTheBill#1]
Hello
Nous avions échangés sous d'autres pseudo à propos de cette apli il y a quelques... années...
https://forum.framasoft.org/viewtopic.php?f=12&t=39505

J'aimerai me replonger dedans...
sais-tu si il y a des incompatibilités majeurs avec une stack plus récente ?
Des trucs à re-développer ?

**Comment by Bertbk** [comment]
Hello !

Je me souviens très bien et je te remercie pour tes retours !

Comme tu le vois, j'ai abandonné le projet. J'avais tout écrit "from scratch" sans framework, ce qui était une très mauvaise idée car mettre à jour le code (et la base de données) devient alors très (trop) compliqué. J'avais commencé à le réécrire en utilisant [le framework Symfony](https://symfony.com/) mais je n'ai pas eu le temps (ni le courage) de continuer.

De plus, avec la RGPD (et même la CNIL), je n'étais pas en règle du tout (pas de CGU, etc.). Même si je n'ai jamais rien fait des données qui étaient collectées (qui sont aujourd'hui supprimées).

Si tu cherches une solution efficace pour partager un budget, je te conseille [CoSpend](https://gitlab.com/eneiluj/cospend-nc) que j'ai découvert il y a quelques semaines : c'est une application Nextcloud vraiment puissante et qui fait tout ce que faisait mon feu Accounter (plusieurs "bills", poids par participants, ...), je ne peux que t'encourager à l'utiliser. Une instance NextCloud avec CoSpend est disponible chez [La Mère Zaclys](http://zaclys.com/), qui fait parti [des CHATONS de Framasoft](https://chatons.org/). On peut de plus inviter des "non-zaclysiens" à éditer (ou pas) un projet. Une application Android, [MoneyBuster](https://gitlab.com/eneiluj/moneybuster),est disponible et permet de synchro les comptes.

Bref, tu es bien entendu libre de forker ce dépôt et le retravailler à ta sauce :-) Si tel est le cas, je crois malheureusement qu'il faut réécrire à l'aide d'un framework efficace (symfony, laravel, ...) ou même pourquoi pas, en nodejs + reactjs (mais là, je n'y connais pas grand chose).
Mais sans vouloir repousser ta motivation, peut être est-il plus efficace de participer à ces projets open-source cités plus haut, qui sont déjà en place et qui fonctionnent très bien ? Cela permettrait de les aider à s'améliorer ? :)
